### ISSUE TITLE
Releases里面下载的Windows版本打不开

### ISSUE THREAD

**Issue by beiwei2008** [AoEiuV020/FlutterDemo#1]
任务管理器有后台进程，但是程序打不开

**Comment by beiwei2008** [comment]
测试了下最后一个可用版本是3.3.10

**Comment by AoEiuV020** [comment]
啊这，我确实没有都测，我再打个最新的研究一下看看，

**Comment by AoEiuV020** [comment]
真的有点奇怪，我 win11 22H2 22621.1413, 
包括最新版3.7.7和3.7.4都一样，也是3.3.10正常，
都是开始一两次打开正常，再打开就只有后台进程没有前台窗口，

搜了一下有其他issue提到这问题， 从1月28日开始就有人提了，居然到3.7.7都还没解决，略坑，
我看看要不要在demo中解决一下，也可能不处理，保留这个bug才知道你运行的是flutter，
https://github.com/flutter/flutter/issues/119415

**Comment by misaka19002** [comment]
It caused by this commit. [https://github.com/flutter/flutter/pull/109816/files/ffc6c36bee544fd6f18b1eca95d2a46be94d9c49]

但是现在很多人都遇到app在后台运行不显示ui的问题。目前已知的解决办法。参考flutter issue #119415

**Comment by misaka19002** [comment]
It caused by this commit. [https://github.com/flutter/flutter/pull/109816/files/ffc6c36bee544fd6f18b1eca95d2a46be94d9c49]

但是现在很多人都遇到app在后台运行不显示ui的问题。目前已知的解决办法。参考flutter issue #119415

**Comment by misaka19002** [comment]
这个commit导致的[https://github.com/flutter/flutter/pull/109816/files/ffc6c36bee544fd6f18b1eca95d2a46be94d9c49]

但是现在很多人都遇到app在后台运行不显示ui的问题。目前已知的解决办法。参考flutter issue #119415

**Comment by AoEiuV020** [comment]
demo已经换成了skeleton模板，貌似就没有这个问题了， 
可能像楼上在flutter那边说的加上了restorationScopeId就不会复现了，

暂且这样吧,flutter那边好像不打算解决了，定级p4一直放着，
我在那边at了一下写出这个bug的人，然后不管了，
