### ISSUE TITLE
https://github.com/flutter/flutter/issues/123853

### ISSUE THREAD

**Issue by GibreelAbdullah** [AoEiuV020/FlutterDemo#2]
https://github.com/flutter/flutter/issues/123853
were you able to solve this?

Sorry, couldn't find any other way to connect.

**Comment by AoEiuV020** [comment]
I haven't been able to resolve this issue completely either. My specific situation is that when compiling a Flutter program using Ubuntu in GitHub Actions, it relies on a higher version of GLIBC. However, stable system repositories like Debian don't have the higher version of GLIBC needed to run the Flutter program.

What's strange is that Flutter programs I compile on my own virtual machine running Ubuntu don't have a dependency on a higher version of GLIBC and can run on Debian. I haven't fully investigated the cause, but it seems that avoiding the generation of Flutter programs using GitHub Actions is the solution for now.
